apiVersion: batch/v1
kind: CronJob
metadata:
  name: pregod-reptile
  namespace: pregod
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
          - image: rss3/pregod-reptile:reptile-gitcoin
            command:
              - ./reptile
              - getresultbystage
            imagePullPolicy: Always
            name: getresultbystage
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - name: config
                mountPath: "/rss3-pregod/config"
                readOnly: true
              - name: mongo-ca
                mountPath: "/rds-combined-ca-bundle.pem"
                subPath: rds-combined-ca-bundle.pem
                readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: config
              secret:
                secretName: pregod
            - name: mongo-ca
              configMap:
                name: rds-combined-ca-bundle.pem
                items:
                  - key: rds-combined-ca-bundle.pem
                    path: rds-combined-ca-bundle.pem
  schedule: "*/20 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
