apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pregod-hub
  namespace: pregod
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`test-pregod.rss3.dev`) && PathPrefix(`/`)
    services:
    - name: pregod-hub-api
      port: 8080
    middlewares:
      - pregod-hub-ratelimit
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pregod-hub-ratelimit
spec:
  rateLimit:
    period: 1m
    average: 600
    sourceCriterion:
      ipStrategy:
        depth: 2
