apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pregod-hub
  namespace: pregod
spec:
  maxReplicas: 12
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pregod-hub
  targetCPUUtilizationPercentage: 70
