version: "3"

services:
  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432

  mongodb:
    restart: always
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - '5672:5672'
